name: Build

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # Install Linux dependencies
      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get -y update && sudo apt -y install bsdtar lzip rpm binutils libopenjp2-tools

      # Download code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      # Build webapp
      - name: Build webapp
        run: npm install && npm run build:web

      # Build and release app
      - name: Build and release app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_build: true
          release: ${{ startsWith(github.ref, 'refs/tags/') }}

      # Release webapp
      - name: Release webapp
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true # Automatically remove deleted files from the deploy branch
